### ISSUE TITLE
How long does the training take for semi-supervised setting? (e.g. 20%)

### ISSUE THREAD

**Issue by lambert-x** [vt-vl-lab/video-data-aug#1]
Hi, 
Thanks for your great work. May I know the time you take for training with your configuration? I train with the semi-20% (ucf-101) setting and the process seems to be extremely slow.

**Comment by Yuliang-Zou** [comment]
Yes, the bottleneck part is the human detection loading and augmentation. You can disable this augmentation by the following modification. Take [20% UCF](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py) as an example:
- Remove [L64](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py#L64) and [L69](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py#L69).
- Remove the suffix "WithBox" in L65-L68
- Reduce the training epoch by half in [L154](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py#L154)

Then the training time should be similar to supervised training on the whole UCF dataset.

**Comment by lambert-x** [comment]
Thank you very much. BTW, do you have a result with this setting? I get top1: 34.66 / top5: 58.95 and want to check if this result makes sense.

**Comment by PeiqinZhuang** [comment]
> Yes, the bottleneck part is the human detection loading and augmentation. You can disable this augmentation by the following modification. Take [20% UCF](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py) as an example:
> 
> * Remove [L64](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py#L64) and [L69](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py#L69).
> * Remove the suffix "WithBox" in L65-L68
> * Reduce the training epoch by half in [L154](https://github.com/vt-vl-lab/video-data-aug/blob/main/configs/semi/r3d_r18_8x8x1_360e_ucf101_rgb_all_20percent_vidssl.py#L154)
> 
> Then the training time should be similar to supervised training on the whole UCF dataset.

Hi, I wonder how long the training time is when training the whole UCF dataset, e.g., the config for  r2plus1d_r34_8x8x1_180e_ucf101_rgb. This information would be useful in helping me to identify if the training process of mine is too slow.

**Comment by Yuliang-Zou** [comment]
@PeiqinZhuang ~2 days should be enough.
