### ISSUE TITLE
Question about the split of hmdb51

### ISSUE THREAD

**Issue by PeiqinZhuang** [vt-vl-lab/video-data-aug#4]
Hi,

I have checked the data split provided by this repo and found the number of items is large than that of the official one. So I wonder if you have merged the training and validation datasets into one file. In this case, I may need to manually split the above file.

**Comment by Yuliang-Zou** [comment]
Yes, the semi-supervised split actually uses both train and val files. We use exactly the same splits from VideoSSL. Here is what the author said:

"The HMDB51 is too small and biased, and even the supervised (100%) method only achieves 17% on HMDB51 database. During the training, both the training & validation splits are used for sampling training data to make the semi-supervised learning model work."
